# Generated by Django 5.0.7 on 2024-08-07 17:12

import api.models.user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='favorite_recipes',
            field=models.JSONField(default=api.models.user_model.MyCustomUser.recipe_default, verbose_name='Recipes'),
        ),
    ]
